### ISSUE TITLE
Unknown data

### ISSUE THREAD

**Issue by nooitaf** [thebakeryio/meteor-devtools#52]
No app running.. 
only one tab open.. 
open dev-tools options.. 
getting data from some telescope site (i think)  

---

![screen shot 2016-06-14 at 09 11 37](https://cloud.githubusercontent.com/assets/1898194/16034102/0fbc3d22-3210-11e6-9588-3b5945614484.jpg)

--- 

![screen shot 2016-06-14 at 09 04 08](https://cloud.githubusercontent.com/assets/1898194/16033941/4917d082-320f-11e6-913c-83eb4ed3075c.jpg)

--- 

![screen shot 2016-06-14 at 09 02 58](https://cloud.githubusercontent.com/assets/1898194/16033939/45352a0a-320f-11e6-86a7-b0c9f5f6c51c.jpg)

**Comment by markdowney** [comment]
It looks like you were running the app locally with `npm start` hence the dummy data. In order to test the extension on a Meteor app, you'll need to build it as a chrome extension with `npm run chrome` and use "Load unpacked extension..." in chrome://extensions/.
